# Especifica a fonte para as gems
source 'https://rubygems.org'

# Especifica a versão do Ruby
ruby '3.2.2'

# Dependências do projeto
gem 'rails', '~> 8.1.4'
gem 'pg', '~> 1.7' # Para PostgreSQL como banco de dados
gem 'puma', '~> 8.0' # Servidor de aplicação
gem 'sass-rails', '>= 6.0.0'
gem 'webpacker', '~> 5.4.4'

# Gemas de desenvolvimento e teste
group :development, :test do
  gem 'rspec-rails', '~> 8.0'
  gem 'pry', '~> 0.16.0' # Para depuração interativa
end

# Gemas apenas para produção
group :production do
  gem 'uglifier', '>= 4.2.1'
end
